### ISSUE TITLE
css dynamic viewing in different screen widths

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#25]
RG_ID wraps too easily and causes the RG_ID to get out of sync with the Min Limit and Max Limit if the screen is narrower than about 1000px.  Min and Max need to follow along with RG_ID, or make RG_ID fixed width to keep from wrapping.

**Comment by troddick** [comment]
![image](https://cloud.githubusercontent.com/assets/1580076/23525356/ceea192e-ff53-11e6-9dbe-89df6bf8d7a0.png)

I can make that thead<th> have a col-md-2 rather than col-md-1, but it will still wrap as the screen size shrinks. Hoping responsive design will solve this.

**Comment by mitch-wim** [comment]
Alright, so to stop it from wrapping, the element should have
`white-space: nowrap;`

Since there are no classes on the elements, I think the only way to do it would be to add that inline to whatever element needs to stop wrapping (all the RG_ID: XX text).

It can't be done to the entire table, because that would prevent other text from wrapping, which would make longer descriptions/text flow into other spaces.

**Comment by troddick** [comment]
fixed
