### ISSUE TITLE
Limit agencies in sidebar drop down

### ISSUE THREAD

**Issue by Anders-Hopkins** [USGS-WiM/NSS#250]
Return only the agencies from the available stations to the agency drop-down in the gagestats sidebar.

**Comment by kjacobsen16** [comment]
I don't know that we can do this like we are with NSS. The stations table is huge (36k stations), so what we get from the services is a paginated return (see the options for pagination in the [service documentation](https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations)). So we don't currently have a way of knowing what agencies are used in the available stations. I think just having the entire list of agencies is fine, since it's a small list anyway.
