### ISSUE TITLE
Batch Upload

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#276]
An average report could have between 40-100 equations to add to NSS. If we could do something like an "Import from Excel" option, that would be helpful.

**Comment by kjacobsen16** [comment]
After a discussion with Pete, this issue should be prioritized. I'll find an example of the excel input they usually have.

I think we'll have to have a separate page for batch upload, it's too much information to show in a modal because they'll have the normal equation info, required params, example values, etc. for several equations.

**Comment by kjacobsen16** [comment]
CSV template - https://doimspp.sharepoint.com/:x:/r/sites/StreamStatsTeam/_layouts/15/doc2.aspx?sourcedoc=%7B3F3FD534-631B-4F0C-A33C-E610E73F1BC5%7D&file=Copy%20of%20NSS%20Log-20180412.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=90578d3a-ce67-4f8b-9b65-19ca6f8f5152

Here's an example from a recent report:
[CT_Import-PeakFlow.xlsx](https://github.com/USGS-WiM/NSS/files/5203596/CT_Import-PeakFlow.xlsx)

This will likely take some planning to incorporate this. Ryan is going to send me the executable for the current equation editor, so we might be able to pull some of that code out (no clue what it's written in)

**Comment by kjacobsen16** [comment]
I forgot this was waiting on me.. Came here to note that with batch upload we're not going to require test values, just check that the expression is valid - depends on https://github.com/USGS-WiM/NSSServices/issues/177

**Comment by kjacobsen16** [comment]
@harper-wavra do you have time to meet about this and walk through the csv template together? I think we should prioritize this.

I looked at the template and I think it has everything we need (although I'm double checking w/ Ryan on usage to see if it makes sense to change it or not).

**Comment by kjacobsen16** [comment]
After a discussion with Pete and Ryan, we may not need this anymore. If we are able to open this up to water science center users soon, having them add the equations one at a time through the add scenario modal might make the most sense in the long run.

Leaving this open for now in case we think of a case in which that will not work.

**Comment by kjacobsen16** [comment]
@harper-wavra we are back to wanting this after a discussion with Pete. Some additional points:
1. We want a user to be able to export an equation selection to the template used for batch upload, e.g. get all equations within x regression region, which they will then edit and re-upload when ready.
2. We want a template file available for download in case they don't want to replicate an existing set of equations

**Comment by kjacobsen16** [comment]
I'm attaching an edited template. Some notes:

1. The green sheets are just pulling in our services, so that users will more likely pick something from our services. You can ignore those.
2. There's a KJ notes sheet. Most of that is just documenting some changes I made, but I left some notes for you to consider at the bottom. That sheet will need to be removed when the template is added to NSS.
3. This template was filled in by Ryan, I just changed the state and region names.
4. You should be able to replicate a lot of what Anders did for the gagestats batch upload, but (1) it'll only be for uploading equations, so you can skip the initial entity selection, (2) you might need to have a table for each regression region they're adding rather than just the one table, and (3) we might need to make the modal bigger and/or separate out the tables a bit like in the "Edit Scenario" page.

[NSS_Example_Template.xlsx](https://github.com/USGS-WiM/NSS/files/6245083/NSS_Example_Template.xlsx)

**Comment by harper-wavra** [comment]
I was looking through the template and trying to figure out how each item in the template relates to how we add a single new scenario currently. There were two things that confused me a little in the template. 

- The first is where to find the unit type (circled in blue) for the equation in the template?

- The second are the way the errors are labeled in the template. It seems like there are four types of error in the template (SE, SEe, SEp and EYoR.) How do those relate to the errors we currently have (circled in red)?

![image](https://user-images.githubusercontent.com/59063181/116264054-96389180-a73f-11eb-8d52-a28aa1478a4b.png)
![image](https://user-images.githubusercontent.com/59063181/116264181-b5372380-a73f-11eb-89c6-fa7d85dce765.png)

**Comment by kjacobsen16** [comment]
@harper-wavra 1. the unit should be added in there. You can add a column after the DepVar (Statistic) Abbreviation.
2. The EYoR is the Equivalent Years of Record, or "EquivalentYears" for the equation
![image](https://user-images.githubusercontent.com/35497731/116297585-07d50780-a761-11eb-906a-04028855b817.png). The errors generally match up that abbreviation with the error code coming from the services, e.g. SE -> the first error below:
![image](https://user-images.githubusercontent.com/35497731/116299100-e2e19400-a762-11eb-8528-896eec1765b6.png)

I believe the SEe is no longer used separately from the SE but I'm double checking that with Pete and Ryan

**Comment by kjacobsen16** [comment]
@harper-wavra not clear on the SEe yet, but we'll also want the PC (Percent Correct) added with the errors (before EYoR). For the note: "Percent Correct, or PC, is used for logistic regression. For example, a logistic regression might result in a value of either 0 or 1 where the values correspond to perennial or intermittent streams."
