### ISSUE TITLE
Station Edits

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#316]
- [x] Allow user to edit the general station details such as name, code, station type, etc.

- [x] Allow user to delete gage

Since we already have the "Edit Gage" button in the gage page modal, that might be the place for it.

**Comment by kjacobsen16** [comment]
@harper-wavra two small things to add to this while you're at it:

- [x] add in word "page" to the page number 
- [x] Display number of gages (you can get this from the response headers just like the number of pages)

**Comment by harper-wavra** [comment]
One of the last things I have for this issue is to automatically "refresh" the gagestats component to reflect the edits made to the gage. (And maybe #280 already has the code for this for when a new station is added) Do we want, like NSS, to save the filters that have been chosen in the sidebar, if any, or should we clear the filters and show all the gages?
