### ISSUE TITLE
rounding values

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#32]
We need NSS to round computed statistic values and prediction intervals to 3 significant figures, regardless of decimal place.  Anything more implies precision that we don't actually have.  Consider Item 3.7 below when you are deciding when to round these values, since they get used in the charts too.
(Item 3.7 mentioned: I love the hover values and the "Show Data Values" option, but it needs to show rounded numbers just like the results table (perhaps fixing item 2.3 will fix this one too).)

**Comment by troddick** [comment]
Can you give me an example where the values are not being rounded? I am applying a 2-3 decimal place rounding on the returning values in the results table.

**Comment by tkoenigusgs** [comment]
It's the distinction between "significant figures" and "decimal places".  For example: 1234.567 has seven significant figures (digits) and three decimal places.  Proper rounding to three significant figures would mean that you would round it to 1230 with no decimals.    Another example: 123 x 123 = 15129, but we consider the 2 and the 9 to be "insignificant" because they imply more precision than the precision of the two numbers that we multiplied.  So we would round the answer to 15100.  When we are dealing with integers, we feel happy and confident with all 5 digits, but when we are dealing with observed, measured, or estimated numbers (almost all numbers in the scientific world), then we literally round EVERYTHING to a number of digits that matches the source numbers.  In the case of NSS, our source numbers are the user input values, which we limit to 3 decimal places.  Thus, we output the same.  Now, how do you do that?...
In Excel, there isn't actually a built-in function for rounding to significant figures.  Excel only rounds to specified decimals.  Thus, many people use this formula (where RV="Rounded Value" and DV = "Decimal Value" and SF="Significant Figures" that we want to round to):
RV=ROUND(DV,SF-(1+INT(LOG10(ABS(DV)))))
You might have a significant figure rounding function available to you in your coding environment, but if you don't you can use the formula above (substituting "3" for "SF").

**Comment by troddick** [comment]
Done.
