### ISSUE TITLE
Edit Regression Region/Filter Issues

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#321]
If I log in and (1) select a region, (2) edit scenario, (3) click the edit button next to a regression and leave that open (don't save or cancel), then (4) select a new filter and (5) try editing another regression, I get weird issues. I'm guessing we need to reset the item being edited when filters are selected.

**Comment by ghost** [comment]
@kjacobsen16 - I'm looking into this one and tried following these steps. I'm not seeing anything clearly wrong with editing the regressions (I tried it with and without selecting new filters to compare, but I probably just don't know all the ins and outs of what it's supposed to do). Could you show examples of the weird issues? Maybe showing which region/filters you tried would help too.

**Comment by kjacobsen16** [comment]
@09Kathy I just tried it in a couple regions and it's pretty consistent but tricky to replicate.

(1) select Colorado, (2) hit "Edit Scenario", (3) select "Flood-Volume Statistics" under statistic groups, (3) hit the "edit" pencil next to "7 Day 2 Year Maximum (V7D2Y)" in the Regressions table, (4) also select "Peak Flow Statistics" in the statistic groups, (5) hit the "edit" pencil next to "2 Year Peak Flood (PK2)".

Notice that it basically swaps out the 2 Year Peak Flood info for the 7 Day 2 Year Maximum info. I think this is because it's saved under the `itemBeingEdited` variable (I think that's what it's called). I think when filters are triggered, we should just have to cancel the edit (I think there's a function for that but can't remember completely).

**Comment by harper-wavra** [comment]
I was looking at this issue a little more and is seems to be a larger issue with how we are editing the Explanatory Variables and Regressions. The issue seems to be that when editing Explanatory Variables or Regressions, whether you cancel or not, then switch the sidebar filters, edit any Explanatory Variables or Regressions again, whichever row you were previously editing is replaced in the new table.

For example:
(1) select Colorado, (2) hit "Edit Scenario", (3) hit the "edit" pencil next to "Mean Basin Slope from 10m DEM" in the Explanatory Variables, (4) hit the "Cancel Edit", (5) select California, (6) hit "Edit Scenario", (7) hit the "edit" pencil next to "Latitude" in the Explanatory Variables.  You can see that "Mean Basin Elevation" turned to "Mean Basin Slope from 10m DEM" from the previous set of Explanatory Variables.

(1) select Colorado, (2) hit "Edit Scenario", (3) hit the "edit" pencil next to "Mean Annual Precipitation" in the Explanatory Variables, (4) hit the "Cancel Edit", (5) select Connecticut, (6) hit "Edit Scenario", (7) hit the "edit" pencil next to "Drainage Area" in the Explanatory Variables.  This one gives some console errors and creates two empty rows in the table

The same things happen when editing the Regressions as well. Not quite sure how to go about fixing yet, but hopefully this make sense.

**Comment by kjacobsen16** [comment]
@harper-wavra - Kathy was looking into this as well. Just wanted to mention that so there's no duplication of efforts.

My thought was it might be something to do with the `itemBeingEdited` object. We just need to clear that out and reset it when a new object is being edited (I'm assuming).

**Comment by ghost** [comment]
Yep, I grabbed a different issue after my first comment though, so depending on how quickly I switch over to STN I'm not sure whether or not I'll get to it. It seems like it should be as simple as adding calling CancelEditRowClicked() in onStatGrpSelect() if you're in edit mode, but I didn't figure out how to actually do that successfully. There aren't any errors if, as I think Harper was referring to, the order of the rows aren't changed when you add a new filter (this is why I originally didn't see errors).
