### ISSUE TITLE
Hide empty values when editing prediction interval 

### ISSUE THREAD

**Issue by ghost** [USGS-WiM/NSS#341]
![image](https://user-images.githubusercontent.com/46943254/96631437-f4417380-12db-11eb-9c7b-611696aaecda.png)
I must have missed this case in Issue #322 
Steps to reproduce:
1. NSS
2. Select Connecticut
3. Click 'Edit Scenario'
4. Notice there are no values next to 'Covariance Matrix' (the covariance matrix should be hidden)

**Comment by kjacobsen16** [comment]
@09Kathy this is my fault, I realized the covariance matrices had a string that said "null", rather than being an actual null value type.

I switched it back for now so that's working again, I'm trying to figure out some issues with the prediction interval but will make a note to comment on this issue if I change it again

**Comment by ghost** [comment]
@kjacobsen16 , sounds good - thanks for fixing it!
