### ISSUE TITLE
Gage Page Edit Changes

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#354]
When you're editing characteristics or statistics, you can click "edit" on multiple lines, but when you save one, it cancels all other edits.

I can see a user coming in and opening multiple characteristics to edit them and not realize that only one will save, meaning lost work for the user.

We need to either only allow the user to edit one item at a time, or allow for a "save all changes" button.

**Comment by Anders-Hopkins** [comment]
In issue #307, it is set so that only one characteristic or statistic can be edited at a time.

**Comment by ghost** [comment]
Pull is closed, closing this now!

**Comment by harper-wavra** [comment]
We should probably leave this issue open until Anders branch is merged into dev. Maybe when you create your pull request just mention both issues (this one and #307) you were working on.

**Comment by ghost** [comment]
@harper-wavra , I already had opened a pull request for this, but closed it because I looked at what Anders did after our meeting today, and I think his solution is better. I'll leave this open for now, but I don't think it would be great to leave my pull request open because we had two different ways of solving the same problem, so they won't merge well together.

**Comment by ghost** [comment]
Never mind, I see now Harper's comment is directed at Anders's pull request, not mine :)
