### ISSUE TITLE
shorten statistic names in results

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#37]
We need a shorter name in the results table for each statistic.  There are four possible choices:
  Short_name (e.g. PK2), 
  Long_name (e.g. 2_Year_Peak_Flood), 
  Description (e.g. "Maximum instantaneous flow..."), and 
  Alias (e.g. "50% flood").

All of these describe the same statistic.  My first choice would be to use "Alias (short_name)" and then do the same down in the Equations table of the Appendix.  
My second choice would be to follow the StreamStats convention, which uses a modified version of the long_name by replacing the underscores with spaces. 
My third choice would be to use the short_name along with a corresponding "Statistic Definitions" table in the appendix.  
In all cases, I would make sure that we provide the descriptions in a "Statistic Definitions" table below the "Parameter Definitions" table."

**Comment by troddick** [comment]
@jknewson  I included you on this, because I'm very unclear what he means. Is this an additional field we can/should put in the table and return in the response?

**Comment by jknewson** [comment]
Currently we only have shortname (Code), Longname (name) and description (description) tracked in the db, Although it would be pretty straightforward to add an alias field as well. I personally never liked exposing Shortname/code to the public, it assumes the user knows the syntax, using them internally is best IMO. For a shorter name, I would rather do something like the Alias and call it shortname, or something equivalent.

**Comment by tkoenigusgs** [comment]
I generally agree with Jeremy about exposing the 10-digit-max shortname (Code) to the public, because it's embarrassing how much we butcher the variable names to fit them into 10 digits.  On the other hand, we have some long stinkin equations in the database, so it is super cumbersome to use anything longer than 10 digits when we display the equations to the users (even 10 digits is too long when displaying equations, in my opinion).  So where does that leave us?

StreamStats uses code, modified name, and description:

![image](https://cloud.githubusercontent.com/assets/25535974/23563413/f5da4062-001c-11e7-9e15-376774615391.png)

But StreamStats doesn't display the equations (as far as I know).  Howver, NSS **_will_** display equations.  So we need to discuss how we are going to represent all variables (both left and right side of each equation) that is not too cumbersome.  Unfortunately, the shortname is the best thing we have at the moment, but I'm open to suggestions.

**Comment by troddick** [comment]
Not sure where we are with this one or really... what it's about. I've read it over a few times and am still confused on what is being requested.

**Comment by tkoenigusgs** [comment]
I had to re-read this a few times to jog my memory, but the issue comes
down to this:

In the current version of NSS, we produce a report for the user that lists
the equations that were used to compute each statistic for the selected
scenario.  Each equation has a "statistic" variable on the left of the
equals sign, and then one or more independent variables on the right side
of the equation.  All of those variables are currently represented by weird
names like "DRNAREA" (for drainage area) and "STORNWI" (for percent
wetlands from some wetland inventory).  These can make long equations
unnecessarily long and cumbersome.

In fact, some regression authors find them so cumbersome that they refuse
to include them in their studies.  Instead, they choose something like "A"
or "W", as is done in Maine's peak equations
<https://pubs.usgs.gov/sir/2015/5049/pdf/sir2015-5049.pdf> (see page 7).

So this GitHub issue centers around whether we can develop a method for
pairing up a REALLY short variable name with the internal StreamStats
variable name.  This would be done at the time of equation entry into the
database, so Tonia and I agreed that we could put this issue off until she
develops the replacement for the SEE.exe program that is currently used to
enter equations from the regression studies.

-Todd



--------------------------------------------------------------
Todd Koenig, P.E.
Water Mission Area
U.S. Geological Survey
Office: 573-308-3924
email: tkoenig@usgs.gov
---------------------------------------------------------------

**Comment by harper-wavra** [comment]
Hans see this never making up the priority stack. Closing for clean up.
