### ISSUE TITLE
sup script and parentheses in equations

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#47]
Parentheses and superscripts don't look right in the equation list if you filter by Ohio...Peak-Flow...Peak_Flow_Full_Model and compute some results.

**Comment by troddick** [comment]
There are certain limitations to the mathJax library. I could possibly look for parentheses and escape them in the same way I do the Abbrevs of Parameters? I'm not sure if that would make it look better or worse though.

**Comment by tkoenigusgs** [comment]
I've believed all along that "typesetting" or "pretty-printing" equations correctly, every time, regardless of the complexity of each equation, is a tall order for NSSweb.  If we can do it, that's fantastic, we can't really afford to have some of them displayed wrong to make most of them fancy.  So we either need to use a library/method that is very capable, or we need to fall back on straight in-line text (probably a fixed-width font) to display them just like Excel would in the cell formula.

**Comment by troddick** [comment]
@tkoenigusgs 
1. original way with weird open/close parentheses on superscripts.
![image](https://cloud.githubusercontent.com/assets/1580076/23763258/767e87f0-04be-11e7-9f83-35c1630192dc.png)

2. escaping out the open/close parentheses (does not look good. loses the superscript):
![image](https://cloud.githubusercontent.com/assets/1580076/23762993/9604fcd6-04bd-11e7-908a-0684763fb9cd.png)

3. not escaping anything (which was just the parameter abbrev) results in the abbrevs being a part of the equation, but it seems to format it better.
![image](https://cloud.githubusercontent.com/assets/1580076/23763182/38169340-04be-11e7-87e5-c4e4f8d71d7a.png)

I'm not sure how to proceed. Unless @jknewson  knows of a library that can handle these equations better than mathjax, maybe we don't escape the abbrev and let the library include them in the equation?

**Comment by tkoenigusgs** [comment]
I think 3 looks great, and 2 is no worse than what we have today.

Incidentally, I think of "escaping" as a way of directing a program to
plainly display a character that would otherwise perform a special
function, so I'm a little lost on how that term is being used here.  But
the solution doesn't necessarily hinge on my understanding.

-Todd

--------------------------------------------------------------
Todd Koenig, P.E.
Office of Surface Water
U.S. Geological Survey
Office: 573-308-3924
email: tkoenig@usgs.gov
---------------------------------------------------------------

**Comment by troddick** [comment]
You are correct in your assumption. I am 'escaping' the parameter abbreviations so they appear as regular text (see 1) versus letting the mathjax library apply it's formatting to it as part of the formula (see 3).

If you are happy with 3, I agree.
